name: 构建镜像
on:
  #防止fork乱用action设置只能手动触发构建
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 10.8/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            kukudemajia/armv7hf-mariadb:latest
            kukudemajia/armv7hf-mariadb:10.8.2
